openapi: 3.0.0
servers:
  - url: 'https://benr4nyn7k.execute-api.eu-central-1.amazonaws.com/develop'
info:
  description: >-
    E-commerce Producti. An API to add and search products
  version: 1.0.0
  title: Producti
  contact:
    email: maximilien@practical-go-lessons.com
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
paths:
  /products:
    get:
      summary: Get all the existing products
      description: All products will be returned. Products are sorted by name.
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllProducts'
        '500':
          description: Internal Server error
      parameters: [ ]
  /product/{id}:
    get:
      summary: Get a product by ID
      description: Retrieve a product by id
      operationId: getProductById
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server error
        '400':
          description: Bad Request
        '404':
          description: Product was not found
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the product
          schema:
            type: string
  /product:
    get:
      summary: Search a product
      description: Search a product, max number of results 1000.
      operationId: search
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server error
        '400':
          description: Bad Request
      parameters:
        - name: search
          in: query
          required: true
          description: The name of the product you want to search
          schema:
            type: string
    post:
      summary: Create a product
      description: Create a product. Note the id property will be overriden by an UUID generated by the system.
      operationId: create
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server error
        '400':
          description: Bad Request
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
components:
  schemas:
    AllProducts:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    ProductMainProps:
      type: object
      properties:
        name:
          type: string
          example: Alice cloth backpack
        originalPrice:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 8477
            formatted:
              type: string
              example: $84.77
        brand:
          type: object
          properties:
            id:
              type: string
              example: 0
            type:
              type: string
              example: brand
            name:
              type: string
              example: Chloé
            localizedName:
              type: string
              example: chloé
        followers:
          type: integer
          format: int32
          example: 18
        daysOnline:
          type: integer
          format: int32
          example: 41
        viewsSinceLastWeek:
          type: integer
          format: int32
          example: 0
        isPriceDropAlertView:
          type: boolean
        isPriceDropAlertDaysOnline:
          type: boolean
        pictures:
          type: array
          items:
            type: object
            properties:
              alt:
                type: string
                example: alt message
              path:
                type: string
                example: 22865326-1_1.jpg
        priceDropped:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 6869
            formatted:
              type: string
              example: $68.69
        recommendedPrice:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 6869
            formatted:
              type: string
              example: 67.69

    Product:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Alice cloth backpack
        originalPrice:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 8477
            formatted:
              type: string
              example: $84.77
        brand:
          type: object
          properties:
            id:
              type: string
              example: 0
            type:
              type: string
              example: brand
            name:
              type: string
              example: Chloé
            localizedName:
              type: string
              example: chloé
        followers:
          type: integer
          format: int32
          example: 18
        daysOnline:
          type: integer
          format: int32
          example: 41
        viewsSinceLastWeek:
          type: integer
          format: int32
          example: 0
        isPriceDropAlertView:
          type: boolean
        isPriceDropAlertDaysOnline:
          type: boolean
        pictures:
          type: array
          items:
            type: object
            properties:
              alt:
                type: string
                example: alt message
              path:
                type: string
                example: 22865326-1_1.jpg
        priceDropped:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 6869
            formatted:
              type: string
              example: $68.69
        recommendedPrice:
          type: object
          properties:
            currency:
              type: string
              example: EUR
            cents:
              type: integer
              format: int32
              example: 6869
            formatted:
              type: string
              example: 67.69
  links: { }
  callbacks: { }
security: [ ]
