# Options
# stage : the deployment stage

service: producti
frameworkVersion: '>=1.28.0'
custom:
  tableName: ${opt:stage}-producti
  ssmParameterStoreName: /producti/${opt:stage}/secrets
provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  stage: ${opt:stage}
  timeout: 28
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
    minimumCompressionSize: 1024
  environment:
    STAGE: ${opt:stage}
    DYNAMO_TABLE_NAME: ${self:custom.tableName}
    PARAMETER_STORE_NAME: ${self:custom.ssmParameterStoreName}
    ACTIVATE_AWS_LOGS: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:TransactWriteItems
        - dynamodb:UpdateItem
        - dynamodb:ConditionCheckItem
        - dynamodb:BatchWriteItem
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - table/${self:custom.tableName}
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - table/${self:custom.tableName}/*
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  api:
    handler: bin/api
    events: ${file(routes.yml)}
resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE